plugins {
    id 'java'
}

group = 'homework'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {


    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
    testImplementation 'org.testng:testng:7.10.2'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation 'com.github.javafaker:javafaker:1.0.2'
}

test {
    useTestNG()
    systemProperty "groups", System.getProperty("groups")

    testLogging {
        events "passed", "failed", "skipped"
    }
}